# Generated by Django 4.0.6 on 2022-08-02 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='some',
            name='age',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='some',
            name='number',
            field=models.CharField(max_length=12),
        ),
    ]
